// Copyright (c) 2026 VeilAssist. All rights reserved.
// Bundled Google Calendar OAuth credentials.
// This file is auto-generated by scripts/inject-oauth.cjs during CI/build.
// When non-empty, users see a simple one-click "Connect Google Calendar" button.
// To generate for local dev: set VEILASSIST_GOOGLE_CAL_CLIENT_ID and
// VEILASSIST_GOOGLE_CAL_CLIENT_SECRET env vars then run: node scripts/inject-oauth.cjs

module.exports = {
  googleCalClientId: '',
  googleCalClientSecret: '',
}
