/** Auto-generated by scripts/copy-android-apk.cjs — do not edit. */
export const SITE_ANDROID_APK_MANIFEST = {
  "fileName": "VeilAssist-Interview.apk",
  "version": "1.0.0",
  "versionCode": 1,
  "size": 16529463,
  "builtAt": "2026-08-16T19:23:10.084Z"
} as const
