/** Auto-generated by scripts/copy-android-apk.cjs — do not edit. */
export const SITE_ANDROID_APK_MANIFEST = {
  "fileName": "VeilAssist-Interview.apk",
  "version": "1.2.0-stag",
  "versionCode": 3,
  "size": 11967591,
  "builtAt": "2026-08-15T13:46:52.709Z"
} as const
