/** Auto-generated by scripts/copy-android-apk.cjs — do not edit. */
export const SITE_ANDROID_APK_MANIFEST = {
  "fileName": "VeilAssist-Interview.apk",
  "version": "1.2.3-stag",
  "versionCode": 6,
  "size": 12006358,
  "builtAt": "2026-08-15T14:37:59.713Z"
} as const
