/** Auto-generated by scripts/sync-windows-manifest.cjs — do not edit. */
export const SITE_WINDOWS_BUILD_MANIFEST = {
  "version": "2026.08.22.16.02",
  "compactVersion": "2026.822.1602",
  "releaseTag": "v2026.822.1602",
  "installerDownloadUrl": "https://github.com/Shlok0095/VeilAssist/releases/download/v2026.822.1602/VeilAssist-Setup.exe",
  "portableDownloadUrl": "https://github.com/Shlok0095/VeilAssist/releases/download/v2026.822.1602/VeilAssist.exe",
  "builtAt": "2026-08-22T12:35:34.656Z",
  "installerSize": 139878675,
  "portableSize": 139607511,
  "installerSha256": "22e4bc19b12841f60488b54368a74a6c3792e81fbc5b36b711ae2c14c3750fbb"
} as const
