/** Auto-generated by scripts/sync-windows-manifest.cjs — do not edit. */
export const SITE_WINDOWS_BUILD_MANIFEST = {
  "version": "2026.08.20.02.07",
  "compactVersion": "2026.820.207",
  "builtAt": "2026-08-19T20:54:00.218Z",
  "installerSize": 139875534,
  "portableSize": 139604342
} as const
