// SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: MIT

syntax = "proto3";

package nvidia.riva.asr;

option cc_enable_arenas = true;
option go_package = "nvidia.com/riva_speech";

import "riva/proto/riva_audio.proto";
import "riva/proto/riva_common.proto";

service RivaSpeechRecognition {
  rpc Recognize(RecognizeRequest) returns (RecognizeResponse) {}
}

message RecognizeRequest {
  RecognitionConfig config = 1;
  bytes audio = 2;
  nvidia.riva.RequestId id = 100;
}

message RecognitionConfig {
  nvidia.riva.AudioEncoding encoding = 1;
  int32 sample_rate_hertz = 2;
  string language_code = 3;
  int32 max_alternatives = 4;
  bool profanity_filter = 5;
  int32 audio_channel_count = 7;
  bool enable_word_time_offsets = 8;
  bool enable_automatic_punctuation = 11;
  string model = 13;
}

message RecognizeResponse {
  repeated SpeechRecognitionResult results = 1;
  nvidia.riva.RequestId id = 100;
}

message SpeechRecognitionResult {
  repeated SpeechRecognitionAlternative alternatives = 1;
  int32 channel_tag = 2;
  float audio_processed = 3;
}

message SpeechRecognitionAlternative {
  string transcript = 1;
  float confidence = 2;
}
