// Copyright (c) 2026 VeilAssist. All rights reserved.
// Pre-build script: write lib/oauthConfig.js with credentials from env vars.
// Usage: node scripts/inject-oauth.cjs
// Required env vars: VEILASSIST_GOOGLE_CAL_CLIENT_ID, VEILASSIST_GOOGLE_CAL_CLIENT_SECRET

'use strict'
const fs = require('fs')
const path = require('path')

const clientId = String(process.env.VEILASSIST_GOOGLE_CAL_CLIENT_ID || '').trim()
const clientSecret = String(process.env.VEILASSIST_GOOGLE_CAL_CLIENT_SECRET || '').trim()

const outPath = path.join(__dirname, '..', 'lib', 'oauthConfig.js')

if (!clientId || !clientSecret) {
  console.log('[inject-oauth] No credentials provided — oauthConfig.js left with empty values.')
  // Write empty placeholder so the module always exists
  fs.writeFileSync(
    outPath,
    `// Auto-generated by scripts/inject-oauth.cjs\nmodule.exports = { googleCalClientId: '', googleCalClientSecret: '' }\n`,
    'utf8',
  )
  process.exit(0)
}

const content = `// Auto-generated by scripts/inject-oauth.cjs — do not edit manually.
// Bundled Google Calendar OAuth credentials (Desktop app type).
module.exports = {
  googleCalClientId: ${JSON.stringify(clientId)},
  googleCalClientSecret: ${JSON.stringify(clientSecret)},
}
`

fs.writeFileSync(outPath, content, 'utf8')
console.log('[inject-oauth] oauthConfig.js written with credentials.')
